name: Generate Release

on:
  pull_request:
    types:
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set filename
        id: report
        run: |
            echo "::set-output name=report_file_name::fga-eps-mds-${{ github.event.repository.name }}-$(TZ='America/Sao_Paulo' date +'%m-%d-%Y-%H:%M:%S')-${{ github.ref_name }}"

      - name: Get SonarCloud metrics
        run: |
            wget $SONAR_URL -O ${{ steps.report.outputs.report_file_name }}.json
        env:
            SONAR_URL: ${{ secrets.SONAR_URL }}

      - name: Pushes sonar file
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_TOKEN }}
        with:
          source_file: ${{ steps.report.outputs.report_file_name }}.json
          destination_repo: 'fga-eps-mds/2022-2-EuPescador-Doc'
          destination_folder: 'analytics-raw-data'
          user_email: ${{ secrets.GIT_EMAIL}}
          user_name: ${{ secrets.GIT_USER }}
          commit_message: Upload a new metrics from ${{ github.event.repository.name }}